name: "Fetch and Commit"
description: "Greet someone and record the time"
inputs:
  url:
    description: "URL of file to fetch"
    required: true
  path:
    description: "Directory path to print file contents"
    required: true
  message:
    description: "Commit message"
    required: false
    default: "Update data"
  headers:
    description: "Headers for the fetch request"
    required: false
    default: "{}"

outputs:
  diff:
    description: "Boolean: data updated"

runs:
  using: "node16"
  main: "dist/index.js"

branding:
  icon: "arrow-down-circle"
  color: "gray-dark"
